version: '3'
services:
    db:
        build:
            context: ./mysql
            dockerfile: Dockerfile
        env_file: ./mysql/mysql.env
        volumes:
            - "../../rails_env/db-data:/var/lib/mysql"
        ports:
            - "3306:3306"

    app:
        build:
          context: ./rails
          dockerfile: Dockerfile
        env_file: ./rails/rails.env
        volumes:
            - "../../rails_env:/app"
        ports:
            - "3000:3000"
        expose:
            - "80"
        tty: true
        links:
            - db
        working_dir: "/app"

    web:
        build:
          context: ./nginx
          dockerfile: Dockerfile
        volumes:
            - "../../rails_env:/app"
        ports:
          - "80:80"
        links:
            - app
